filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/nginx/logs/*.log
  exclude_files: ["/data/nginx/logs/access.log","/data/nginx/logs/error.log"]
  #multiline.pattern: ^\d{4}\-\d{2}\-\d{2}
  #multiline.negate: true
  #multiline.match: after

filebeat.config.inputs:
  enabled: true
  path: /data/soft/filebeat/filebeat.yml
  reload.enabled: true
  reload.period: 10s

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s


processors:
  - add_host_metadata:
      netinfo.enabled: true



output.kafka:
  hosts: ["172.18.226.150:9092","172.18.226.151:9092","172.18.226.152:9092"]
  topic: 'nginx-%{[host.name]}'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 100000000
